steps:
# Copy the ssh key
# - name: 'gcr.io/cloud-builders/gsutil'
#   args:
#   - cp
#   - 'gs://qqin.page/Keys/cloud_build'
#   - '/root/.ssh/cloud_build'
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh
# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: 'chmod'
#   args:
#   - '400'
#   - '/root/.ssh/cloud_build'
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh
# # Copy known_hosts
# - name: 'gcr.io/cloud-builders/gsutil'
#   args:
#   - cp
#   - 'gs://qqin.page/Keys/known_hosts'
#   - '/root/.ssh/known_hosts'
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - compute
  - ssh
  - service-403422450929@aries-micro
  - --command
  - 'bash -s' < deploy.sh
  # volumes:
  # - name: 'ssh'
  #   path: /root/.ssh
