steps:
# Copy the ssh key
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - cp
  - 'gs://qqin.page/Keys/cloud_build'
  - 'cloud_build'
# Copy known_hosts
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - cp
  - 'gs://qqin.page/Keys/known_hosts'
  - 'known_hosts'
# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - submodule
  - update
  - --init
  - --recursive
  volumes:
  - name: 'ssh'
    path: /root/.ssh
# Copy the files to server
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - 'rsync'
  - -r
  - .
  - service-403422450929@35.196.143.123:/var/virgo --delete
  volumes:
  - name: 'ssh'
    path: /root/.ssh