steps:
# Copy the ssh key
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - cp
  - 'gs://qqin.page/Keys/cloud_build*'
  - '/root/.ssh/'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'chmod'
  args:
  - '400'
  - '/root/.ssh/cloud_build'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
# Copy known_hosts
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - cp
  - 'gs://qqin.page/Keys/known_hosts'
  - '/root/.ssh/known_hosts'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'chmod'
  args:
  - '+x'
  - 'deploy.sh'
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - compute
#   - ssh
#   - service-403422450929@aries-micro
#   - --zone=us-east1-b
#   # - --ssh-key-file=cloud_build
#   - --command='bash -s' < deploy.sh
# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: 'ls'
#   args:
#   - -alG
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'scp'
  args:
  - -i
  - /root/.ssh/cloud_build
  - deploy.sh
  - service-403422450929@35.196.143.123:/var/staging/deploy.sh
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'ssh'
  args:
  - -i
  - /root/.ssh/cloud_build
  - service-403422450929@35.196.143.123
  - 'bash -s < /var/staging/deploy.sh'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
